# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle' # Install Java from Eclipse Temurin (AdoptOpenJDK)
          java-version: '21' # Specify the Java version you need

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

        
      - name: increment version
        run: ./gradlew incrementVersion

         # Commit version change back to repository
      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
           commit_message: Increment version [skip ci]
           file_pattern: 'gradle.properties'
        
      - name: build the docker image and push it
        run: ./gradlew clean build tagAndPushImages

